// Ted IIFE Kurdish

var Fuzzyduck = function (originalFuzzyDuck) {

	let englishKurdishWords = {
    "and": "û",
    "with": "bi",
    "the": "ew",
    "too": "jî",
    "to": "ber",
    "out": "derve",
    "all": "gişt",
    "of": "ji",
    "by": "ji",
    "I": "ez",
    "also": "jî",
    "not": "ne",
    "on": "li",
    "can": "qûtîk",
    "up": "bi jorve",
    "be": "Be",
    "a": "yek",
    "that": "va",
    "you": "hûn",
    "your": "ya te",
    "you’re": "Tu ne",
    "us": "me",
    "this": "ev",
    "is": "e",
    "one": "yek",
    "two": "du",
    "three": "sê",
    "four": "çar",
    "five": "pênc",
    "six": "şeş",
    "seven": "heft",
    "eight": "heşt",
    "nine": "neh",
    "ten": "deh",
    "eleven": "yanzdeh",
    "twelve": "duwanzdeh",
    "merry": "kêfxweş",
    "christmas": "Noel",
    "happy": "şa",
    "new": "nşh",
    "year": "sal",
    "lots": "Gelek",
    "love": "evîn",
    "joy": "kêf",
    "happiness": "qismet",
    "have": "hebûn",
    "yourself": "xwe",
    "holiday": "karbetalî",
    "season": "demsal",
    "trimmings": "Erênî",
    "wishing": "Bixwaze",
    "magical": "Sêrik",
    "decorate": "xemilandin",
    "god": "xwedê",
    "bless": "bereketkirin",
    "lord": "mirze",
    "everyone": "Her kes",
    "hope": "hêvî",
    "wonder": "mûcîze",
    "peace": "aşîtî",
    "holidays": "Betlaneyê",
    "unwrap": "Nedixwe",
    "wrap": "pêçan",
    "joyful": "dilfireh",
    "holly": "Holly",
    "jolly": "Jolly",
    "best": "baştirîn",
    "present": "amade",
    "spend": "xerckirin",
    "time": "dem",
    "little": "kêm",
    "let": "berdan",
    "heart": "dil",
    "light": "sivik",
    "gay": "Gay",
    "most": "zêdeyî",
    "wonderful": "pirxweş",
    "May": "Gulan",
    "thinking": "Difikirin",
    "warmly": "Germ",
    "extra": "biserde",
    "measure": "pîvan",
    "good": "baş",
    "cheer": "kêfhatinî",
    "whatever": "çibe jî",
    "beautiful": "bedew",
    "meaningful": "bimane",
    "sum": "giş",
    "earth": "erd",
    "goodwill": "xêrxwazî",
    "men": "Mêran",
    "women": "Jinên",
    "children": "Zarok",
    "batteries": "Batteries",
    "included": "Tevlî",
    "fruitcake": "Xemgîn",
    "stress": "dûbare",
    "free": "belaş",
    "tell": "gotin",
    "lot": "pirr",
    "about": "ji dor",
    "person": "şexs",
    "way": "rê",
    "they": "ew",
    "handle": "destik",
    "things": "Tiştan",
    "rainy": "baranî",
    "day": "roj",
    "lost": "windabû",
    "luggage": "bar",
    "tangled": "Teng",
    "lights": "Ronahî",
    "crazy": "dîn",
    "baby": "bebek",
    "cold": "sarma",
    "outside": "li derve",
    "fa": "Fa",
    "la": "La",
    "ho": "Ho",
    "enjoy": "hizkirin",
    "cherish": "Xemgîn",
    "together": "bihevra",
    "cookies": "Cookie",
    "dreidel": "Dreidel",
    "menorah": "Menorah",
    "spin": "hûnîn",
    "latke": "Latke",
    "festival": "cejn",
    "hugs": "Hugs",
    "kisses": "Destûr",
    "friends": "Hevalên xwe",
    "friend": "heval",
    "hoping": "Hêvî dikir",
    "see": "dîtin",
    "soon": "nêzda",
    "warm": "germ",
    "regards": "Behsa",
    "greetings": "Silav",
    "another": "yekî din",
    "great": "ecêb",
    "hanukah": "Hanukah",
    "chanukah": "Chanukah",
    "candles": "Şam",
    "nights": "Şev",
    "heath": "Hewa",
    "family": "malbat",
    "shine": "birq",
    "down": "jêr",
    "upon": "li ser",
    "miracle": "mûcîze",
    "guides": "Rêber",
    "through": "Bi rêya",
    "tough": "dijwar",
    "times": "Carinan",
    "celebration": "kêfî",
    "special": "taybetî",
    "here": "vir",
    "made": "Çêkirin",
    "clay": "herrî"
  	};

  	originalFuzzyDuck.translateToKurdish = function(arrToTranslate) {

  		// Translation logic here
  		return translatedText;
  	};



}(Fuzzyduck);